In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [66]:
# The code was removed by Watson Studio for sharing.

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [67]:
data.head(1)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [68]:
x=data[['Gender','Age',
       'EstimatedSalary']].values

In [69]:
y=data[['Purchased']].values

In [70]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [71]:
x[:,0]=le.fit_transform(x[:,0])

In [73]:
x[0]

array([1, 19, 19000], dtype=object)

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [76]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [77]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [78]:
x_test[0]

array([ 1.02532046, -0.79895082,  0.49460758])

In [79]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf') #kernel = 'linear'
classifier.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [80]:
y_pred = classifier.predict(x_test)

In [81]:
y_pred[1:10]

array([0, 0, 0, 0, 0, 0, 1, 0, 1])

In [82]:
y_test[1:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0]])

In [83]:
x_test[0]

array([ 1.02532046, -0.79895082,  0.49460758])

In [84]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred,y_test)

In [85]:
score*100

95.0

In [86]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[55,  1],
       [ 3, 21]])

In [87]:
!pip install watson-machine-learning-client --upgrade

Requirement already up-to-date: watson-machine-learning-client in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (1.0.365)
Requirement not upgraded as not directly required: urllib3 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (1.22)
Requirement not upgraded as not directly required: ibm-cos-sdk in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.0.1)
Requirement not upgraded as not directly required: tabulate in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (0.8.2)
Requirement not upgraded as not directly required: tqdm in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (4.19.5)
Requirement not upgraded as not directly required: requests in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.18.4)
Requirement not upgraded as not direct

In [88]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [89]:
# The code was removed by Watson Studio for sharing.

In [90]:
client=WatsonMachineLearningAPIClient(wml)

In [91]:
model_props={
    client.repository.ModelMetaNames.AUTHOR_NAME:"Prashanth",
    client.repository.ModelMetaNames.AUTHOR_EMAIL:"vissaprashanth@gmail.com",
    client.repository.ModelMetaNames.NAME:"Social_Network_Ads SVM"
}

In [92]:
model_artifact=client.repository.store_model(classifier,meta_props=model_props)

In [93]:
published_model_uid=client.repository.get_model_uid(model_artifact)

In [94]:
published_model_uid

'f2a0b557-af82-4678-b769-aeb7586ec04b'

In [95]:
deploy=client.deployments.create(published_model_uid,name="Purchased ?")



#######################################################################################

Synchronous deployment creation for uid: 'f2a0b557-af82-4678-b769-aeb7586ec04b' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='45703787-429e-4331-874e-bc33b029ee06'
------------------------------------------------------------------------------------------------




In [63]:
scoring_endpoint=client.deployments.get_scoring_url(deploy)

In [64]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/0a71b0b0-97d0-4b0d-b404-0cbcecf447fe/deployments/eda5d2fd-f394-4aa7-82e3-6a7b28349210/online'

In [ ]:
#HTTP GET request ... basic resposnse is token
#save token
#http post ... token & input... response is prediction